config/routes.rb
require 'sidekiq/web'

UpdateTestlink::Application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'
  resources :old_test_cases
  post 'testlink/update_status'
  post 'testlink/update_automation_test_name'

end

app/models/old_test_case.rb
class OldTestCase < ActiveRecord::Base
  #paginates_per 50
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/old_test_cases_controller.rb
class OldTestCasesController < ApplicationController

  # GET /old_test_cases
  # GET /old_test_cases.json
  def index
    # @old_test_cases = OldTestCase.all
    @old_test_cases = OldTestCase.order(:test_link_id).page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @old_test_cases }
    end
  end

  # GET /old_test_cases/1
  # GET /old_test_cases/1.json
  def show
    @old_test_case = OldTestCase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @old_test_case }
    end
  end

  # GET /old_test_cases/new
  # GET /old_test_cases/new.json
  def new
    @old_test_case = OldTestCase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @old_test_case }
    end
  end

  # GET /old_test_cases/1/edit
  def edit
    @old_test_case = OldTestCase.find(params[:id])
  end

  # POST /old_test_cases
  # POST /old_test_cases.json
  def create
    @old_test_case = OldTestCase.new(params[:old_test_case])

    respond_to do |format|
      if @old_test_case.save
        format.html { redirect_to @old_test_case, notice: 'Old test case was successfully created.' }
        format.json { render json: @old_test_case, status: :created, location: @old_test_case }
      else
        format.html { render action: "new" }
        format.json { render json: @old_test_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /old_test_cases/1
  # PUT /old_test_cases/1.json
  def update
    @old_test_case = OldTestCase.find(params[:id])

    respond_to do |format|
      if @old_test_case.update_attributes(params[:old_test_case])
        format.html { redirect_to @old_test_case, notice: 'Old test case was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @old_test_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /old_test_cases/1
  # DELETE /old_test_cases/1.json
  def destroy
    @old_test_case = OldTestCase.find(params[:id])
    @old_test_case.destroy

    respond_to do |format|
      format.html { redirect_to old_test_cases_url }
      format.json { head :ok }
    end
  end
end

app/controllers/testlink_controller.rb
class TestlinkController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  def update_status
    if params[:case_arrays]
      temp = OldTestCase.where(:case_id => params[:case_arrays]).select("test_link_id, automated_status")
      test_link_ids = temp.select{|i| i.automated_status != 'Update Needed' and i.automated_status != 'Not Ready for Automation'}.map{|i| i.test_link_id}
      UpdateStatusWorker.perform_async(test_link_ids)      
      render nothing: true
    else
      render text: "Failed to find case arrays in requests"
    end
  end

  def update_automation_test_name

    if params[:script_name] && params[:test_cases]
      test_link_ids = OldTestCase.where(:case_id => params[:test_cases]).select("test_link_id").map{|i| i.test_link_id}
      UpdateAutomationTestNameWorker.perform_async(params[:script_name], test_link_ids)
      render nothing: true
    else
      render text: "Failed to find script name and case arrays in requests"
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/old_test_cases_helper.rb
module OldTestCasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UpdateTestlink</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/old_test_cases/_form.html.erb
<%= form_for(@old_test_case) do |f| %>
  <% if @old_test_case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@old_test_case.errors.count, "error") %> prohibited this old_test_case from being saved:</h2>

      <ul>
      <% @old_test_case.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :test_plan_id %><br />
    <%= f.number_field :test_plan_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :case_id %><br />
    <%= f.text_field :case_id %>
  </div>
  <div class="field">
    <%= f.label :version %><br />
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </div>
  <div class="field">
    <%= f.label :automated_status %><br />
    <%= f.text_field :automated_status %>
  </div>
  <div class="field">
    <%= f.label :test_link_id %><br />
    <%= f.number_field :test_link_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/old_test_cases/edit.html.erb
<h1>Editing old_test_case</h1>

<%= render 'form' %>

<%= link_to 'Show', @old_test_case %> |
<%= link_to 'Back', old_test_cases_path %>

app/views/old_test_cases/index.html.erb
<h1>Listing old_test_cases</h1>

<table>
  <tr>
    <th>Case ID</th>
    <th>Automated status</th>
    <th>Testlink ID</th>
    <th></th>
  </tr>

<% @old_test_cases.each do |old_test_case| %>
  <tr>
    <td><%= old_test_case.case_id %></td>
    <td><%= old_test_case.automated_status %></td>
    <td><%= old_test_case.test_link_id %></td>
    <td><%= button_to 'Update Status' %></td>
  </tr>
<% end %>
</table>

<br />
<%= paginate @old_test_cases %>
<%= link_to 'New Old test case', new_old_test_case_path %>

app/views/old_test_cases/new.html.erb
<h1>New old_test_case</h1>

<%= render 'form' %>

<%= link_to 'Back', old_test_cases_path %>

app/views/old_test_cases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Test plan:</b>
  <%= @old_test_case.test_plan_id %>
</p>

<p>
  <b>Name:</b>
  <%= @old_test_case.name %>
</p>

<p>
  <b>Case:</b>
  <%= @old_test_case.case_id %>
</p>

<p>
  <b>Version:</b>
  <%= @old_test_case.version %>
</p>

<p>
  <b>Priority:</b>
  <%= @old_test_case.priority %>
</p>

<p>
  <b>Automated status:</b>
  <%= @old_test_case.automated_status %>
</p>

<p>
  <b>Test link:</b>
  <%= @old_test_case.test_link_id %>
</p>


<%= link_to 'Edit', edit_old_test_case_path(@old_test_case) %> |
<%= link_to 'Back', old_test_cases_path %>